                                                    Numpy Practice
                                                syed Qasim Raza Fatimi

In [1]:
import numpy as np
import pandas as pd

In [2]:
print('numpy:', np.__version__)

numpy: 1.22.3


In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [4]:
arr=np.array([1,2,3,4,4])
arr

array([1, 2, 3, 4, 4])

In [5]:
bool_arr=np.array([0,1,0,0,-1],dtype='bool')
bool_arr

array([False,  True, False, False,  True])

In [6]:
type(arr)


numpy.ndarray

In [7]:
type(bool_arr)

numpy.ndarray

In [8]:
arr2=np.array((1,3,4,5))
arr2

array([1, 3, 4, 5])

# Array indexing

In [9]:
#2d array
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
t

array([[1, 2, 3, 4, 5],
       [3, 5, 6, 7, 8]])

In [10]:
#3d array
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,8]],[[2,5,4,3,4],[3,5,6,7,8]]])
arr3

array([[[1, 2, 3, 4, 5],
        [3, 5, 6, 7, 8]],

       [[2, 5, 4, 3, 4],
        [3, 5, 6, 7, 8]]])

In [11]:
#to check dimention
print(arr.ndim)
print(t.ndim)
print(arr3.ndim)

1
2
3


In [12]:
#size of array
arr3.size

20

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
arr = np.array([1, 2, 3, 4])
arr[3]

4

In [15]:
arr[1]+arr[3]

6

In [16]:
#accesing element of 2D array
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
t[1,3]

7

In [17]:
#for 3D array
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,8]],[[2,5,4,3,4],[3,5,6,7,8]]])
arr3[1,0,2]

4

In [18]:
#negative indexing
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
t[1,-1]

8

### Array Shape

In [19]:
#shape of array
arr.shape

(4,)

In [20]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [21]:
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,4]],[[2,5,4,3,4],[3,5,6,7,8]]])
arr3.shape

(2, 2, 5)

## NumPy Array Reshaping

In [22]:
#1-D to 2-D
arr = np.array([1, 2, 3, 4,4,5,6,8,8,9])
new=arr.reshape(2,5)
new

array([[1, 2, 3, 4, 4],
       [5, 6, 8, 8, 9]])

In [23]:
#1-D to 3-D
arr = np.array([1, 2, 3, 4,4,5,6,8,8,9,1,2])
new=arr.reshape(2,3,2)
new

array([[[1, 2],
        [3, 4],
        [4, 5]],

       [[6, 8],
        [8, 9],
        [1, 2]]])

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)     #returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [25]:
# converting a multidimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
new = arr.reshape(-1)
print(new)

[1 2 3 4 5 6]


# Slicing

In [26]:
#array slicing
arr=np.array([1, 2, 3, 4])
arr[0:2]

array([1, 2])

In [27]:
arr[2:]

array([3, 4])

In [28]:
arr[:3]

array([1, 2, 3])

In [29]:
#negative slicing
arr[-3:-1]

array([2, 3])

In [30]:
arr[:-1]

array([1, 2, 3])

In [31]:
arr[0:4:2]

array([1, 3])

In [32]:
arr[::2]

array([1, 3])

In [33]:
# Slicing 2-D Arrays
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
t[1,0:2]

array([3, 5])

In [34]:
# From both elements, return index 2:
t[0:2,2]

array([3, 6])

In [35]:
t[0:2,2:4]

array([[3, 4],
       [6, 7]])

# Numpy Data Types


In [36]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# # V - fixed chunk of memory for other type ( void )

In [37]:
arr=np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [38]:
ar=np.array(['qasim','haider','khawer'])
print(ar.dtype)

<U6


In [39]:
arr=np.array([1, 2, 3, 4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [40]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [41]:
# Converting Data Type on Existing Arrays
arr = np.array([1, 2, 3, 4])
new_arr=arr.astype('S')
new_arr

array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [42]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# Array Copy and View

In [43]:
arr = np.array([1, 2, 3, 4])
c=arr.copy()
c[0]=22
print(arr)
print(c)

[1 2 3 4]
[22  2  3  4]


In [44]:
arr = np.array([1, 2, 3, 4])
c=arr.view()
c[0]=22
print(arr)
print(c)

[22  2  3  4]
[22  2  3  4]


In [45]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()   #array own data and return none
y = arr.view()    #doesn't own data and return array
print(x.base)   
print(y.base)

None
[1 2 3 4 5]


# Array Iterating

In [46]:
# 1-D
arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x)

1
2
3
4


In [47]:
#2-D
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
for x in t:
    print(x)

[1 2 3 4 5]
[3 5 6 7 8]


In [48]:
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
for x in t:
    for y in x:
        print(y)

1
2
3
4
5
3
5
6
7
8


In [49]:
#3-D array
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,8]],[[2,5,4,3,4],[3,5,6,7,8]]])
for x in arr3:
    print(x)

[[1 2 3 4 5]
 [3 5 6 7 8]]
[[2 5 4 3 4]
 [3 5 6 7 8]]


In [50]:
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,8]],[[2,5,4,3,4],[3,5,6,7,8]]])
for x in arr3:
    for y in x:
        print(y)
    

[1 2 3 4 5]
[3 5 6 7 8]
[2 5 4 3 4]
[3 5 6 7 8]


In [51]:
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,8]],[[2,5,4,3,4],[3,5,6,7,8]]])
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
3
5
6
7
8
2
5
4
3
4
3
5
6
7
8


In [52]:
# Iterating Arrays Using nditer()
arr3=np.array([[[1,2,3,4,5],[3,5,6,7,8]],[[2,5,4,3,4],[3,5,6,7,8]]])
for x in np.nditer(arr3):
    print(x)

1
2
3
4
5
3
5
6
7
8
2
5
4
3
4
3
5
6
7
8


In [53]:
# Iterating Array With Different Data Types
arr3=np.array([1,2,3,4,5])
for x in np.nditer(arr3, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


In [54]:
t=np.array([[1,2,3,4,5],[3,5,6,7,8]])
for x in np.nditer(t[:,::3]):
    print(x)

1
4
3
7


In [55]:
# Enumerated Iteration Using ndenumerate()
arr3=np.array([1,2,3,4,5])
for x in np.ndenumerate(arr3):
    print(x)

((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)
((4,), 5)


# Joining NumPy Array

In [56]:
#concatenate
arr3=np.array([1,2,3,4,5])
arr4=np.array([5,7,6,5,5])
arr=np.concatenate((arr3,arr4))
arr

array([1, 2, 3, 4, 5, 5, 7, 6, 5, 5])

In [57]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [58]:
#stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [59]:
#hstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [60]:
#vstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [61]:
#dstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Array

In [62]:
#1-D
arr4=np.array([5,7,6,5,5,5])
arr=np.split(arr4,3)
arr

[array([5, 7]), array([6, 5]), array([5, 5])]

In [63]:
# Splitting 2-D Arrays
arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr=np.split(arr2,3)
arr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [64]:
# Splitting 2-D Arrays
arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr=np.split(arr2,2,axis=1)
arr

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

In [65]:
# hsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new = np.hsplit(arr, 3)
print(new)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [66]:
#  where() method.
arr4=np.array([5,7,6,5,5,5])
x=np.where(arr4==6)
x

(array([2], dtype=int64),)

In [67]:
#  indexes where the values are even
arr4=np.array([2,4,5,6,7,8])
x=np.where(arr4%2==0)
x

(array([0, 1, 3, 5], dtype=int64),)

In [68]:
# searchsorted()
arr=np.array([1,3,4,5,6,7,6])
x=np.searchsorted(arr,5)
x

3

In [69]:
# indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


# Sorting Arrays

In [70]:
# Sorting Arrays
arr=np.array([1,3,4,5,6,7,6])
x=np.sort(arr)
x

array([1, 3, 4, 5, 6, 6, 7])

In [71]:
# string
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [72]:
# boolian
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [73]:
t=np.array([[1,4,5,2,3],[3,5,8,7,6]])
print(np.sort(t))

[[1 2 3 4 5]
 [3 5 6 7 8]]


# Filter Array

In [74]:
# Filter Array
arr=np.array([1,4,5,2,3])
x=[True,False,True,True,False]
new=arr[x]
new

array([1, 5, 2])

In [75]:
arr=np.array([1,4,5,2,3])
filter_arr=[]
for i in arr:
    if i>2:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new=arr[filter_arr]
print(filter_arr)
print(new)

[False, True, True, False, True]
[4 5 3]


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new = arr[filter_arr]
print(filter_arr)
print(new)

[False, True, False, True, False, True, False]
[2 4 6]


In [77]:
# Creating Filter Directly From Array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr=arr%2==0
new=arr[filter_arr]
new

array([2, 4, 6])

# Random Numbers in NumPy

In [78]:
from numpy import random

In [79]:
# random number b/t 1-100
x=random.randint(100)
x

33

In [80]:
# Generate Random Float
x=random.rand()
x

0.517305474622726

In [81]:
# Random Array(1-D)
x=random.randint(100,size=5)
x

array([ 0, 11, 93, 18, 48])

In [82]:
x=random.rand(5)
x

array([0.1198132 , 0.56488966, 0.37837064, 0.63551338, 0.35970927])

In [83]:
# 2-D
x=random.randint(100,size=(3,4))
x

array([[61, 63, 53, 18],
       [ 3, 77, 40, 93],
       [72, 61, 94, 15]])

In [84]:
x=random.rand(3,4)
x

array([[0.91060584, 0.9396202 , 0.29990491, 0.62449396],
       [0.77221079, 0.66588682, 0.17773541, 0.09869656],
       [0.22108347, 0.21534502, 0.74052595, 0.49890933]])

In [85]:
# choice
x = random.choice([3, 5, 7, 9])
print(x)

3


In [86]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 9 9 5 3]
 [5 5 3 3 3]
 [5 3 3 7 3]]


In [87]:
# Random Distribution

In [88]:
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.1
# The probability for the value to be 5 is set to be 0.3
# The probability for the value to be 7 is set to be 0.6
# The probability for the value to be 9 is set to be 0
x = random.choice([3, 5, 7, 9], p=[0.2, 0.3, 0.5, 0.0],size=(10))  #The sum of all probability numbers should be 1 
print(x)

[7 7 5 5 5 7 7 3 7 5]


In [89]:
x = random.choice([3, 5, 7, 9],p=[0.3,0.7,0.0,0.0],size=(3,5))
x

array([[5, 5, 5, 5, 5],
       [5, 3, 5, 5, 5],
       [5, 3, 5, 3, 5]])

# Random Permutations

In [90]:
# Shuffling Arrays
arr=np.array([1,2,3,4,5])
random.shuffle(arr)   #he shuffle() method makes changes to the original array.
arr

array([3, 1, 5, 2, 4])

In [91]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))#The permutation() method returns a re-arranged array

[4 2 5 1 3]


In [92]:
arr 

array([1, 2, 3, 4, 5])

# Normal Distribution

In [93]:
x = random.normal(size=(3, 3))
print(x)

[[ 0.5472444   0.81690641  1.24547237]
 [-1.89108475  0.40130557 -1.16720971]
 [ 0.89711977 -0.92733916  0.41537851]]


In [94]:
x=random.normal(loc=1,scale=2,size=(2,3))
x

array([[-0.71075623,  2.2274238 , -1.73526597],
       [ 1.83836663, -0.03678993,  1.5633417 ]])

## Binomial Distribution

In [95]:
x=random.binomial(n=10,p=0.2,size=10)
x

array([4, 2, 4, 2, 3, 3, 4, 1, 2, 2])

## Poisson Distribution

In [96]:
x=random.poisson(lam=2,size=10)
x

array([1, 0, 5, 0, 0, 0, 1, 1, 1, 0])

## Uniform Distribution

In [97]:
x=random.uniform(size=(2,3))
x

array([[0.10902686, 0.38194565, 0.06786538],
       [0.04461346, 0.84400904, 0.26057823]])

## Logistic Distribution

In [98]:
x=random.logistic(loc=1,scale=2,size=(2,3))
x

array([[ 7.04673107,  6.61768666,  3.20097195],
       [ 0.93420802, -1.779311  ,  3.36964035]])

## Multinomial Distribution

In [99]:
x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
print(x)

[1 0 2 1 2 0]


## Exponential Distribution

In [100]:
x=random.exponential(scale=2,size=(2,3))
x

array([[1.5157203 , 0.68795312, 0.26387438],
       [0.08142016, 0.09331851, 6.39790564]])

## Chi Square Distribution

In [101]:
x=random.chisquare(df=3,size=(2,3))
x

array([[2.98367647, 3.42887486, 1.4753517 ],
       [1.04570352, 3.1714742 , 1.50916413]])

## Rayleigh Distribution

In [102]:
x=random.rayleigh(scale=2,size=(2,3))
x

array([[4.09641312, 1.3480207 , 2.36355437],
       [1.41544605, 2.00706758, 1.51297481]])

## Pareto Distribution

In [103]:
x=random.pareto(a=3,size=(2,3))
x

array([[0.22662318, 0.79553407, 0.0598186 ],
       [0.10953845, 0.34381936, 0.08642192]])

## Zipf Distribution

In [104]:
x=random.zipf(a=3,size=(2,3))
x

array([[1, 1, 1],
       [2, 1, 1]])

# Numpy Universal Functions

In [105]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=[]
for i,j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 8, 8]


In [106]:
# Ufunc in numpy
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.add(x,y)
z

array([5, 7, 9, 8, 8])

In [107]:
# Create Your Own ufunc
def summ(x,y):
    return x+y
summ=np.frompyfunc(summ,2,1)
print(summ([1,2,3],[2,3,4]))
    

[3 5 7]


In [108]:
print(type(summ))

<class 'numpy.ufunc'>


In [109]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.subtract(x,y)
z

array([-3, -3, -3,  0,  2])

In [110]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.multiply(x,y)
z

array([ 4, 10, 18, 16, 15])

In [111]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.divide(x,y)
z

array([0.25      , 0.4       , 0.5       , 1.        , 1.66666667])

In [112]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.power(x,y)
z

array([  1,  32, 729, 256, 125])

In [113]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.mod(x,y)
z

array([1, 2, 3, 0, 2])

In [114]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.remainder(x,y)
z

array([1, 2, 3, 0, 2])

In [115]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.divmod(x,y)
z

(array([0, 0, 0, 1, 1]), array([1, 2, 3, 0, 2]))

In [116]:
x=[-1,2,-3,4,-5]

z=np.absolute(x)
z

array([1, 2, 3, 4, 5])

#### Rounding Decimals

In [117]:
x=np.trunc(3.45)
x

3.0

In [118]:
x=np.fix(-3.34)
x

-3.0

In [119]:
x= np.around(3.1666, 2)
print(x)

3.17


In [120]:
x=np.floor([-3.1666])
x

array([-4.])

In [121]:
x=np.ceil(2.33)
x

3.0

# NumPy Logs

In [122]:
# Log at Base 2
x=np.arange(1,5)
print(np.log2(x))

[0.        1.        1.5849625 2.       ]


In [123]:
# Log at Base 10
x=np.arange(1,6)
print(np.log10(x))


[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [124]:
# Natural Log, or Log at Base e
x=3
print(np.log(x))

1.0986122886681098


In [125]:
# Log at Any Base
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


# NumPy Summations

In [126]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
print(np.sum([x,y]))

37


In [127]:
# alternate method for sum using loop
x=np.add(x,y)
print(x)
summ=0
for i in x:
    summ=summ+i
print(summ)

[5 7 9 8 8]
37


In [128]:
# Summation Over an Axis
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.sum([x,y],axis=1)
z

array([15, 22])

In [129]:
# Cummulative Sum
# Cummulative sum means partially adding the elements in array.\
# The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
x=np.array([1, 2, 3, 4])
print(np.cumsum(x))

[ 1  3  6 10]


# NumPy Products

In [130]:
x=np.array([1, 2, 3, 4])
print(np.prod(x))

24


In [131]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.prod([x,y])
z

172800

In [132]:
x=[1,2,3,4,5]
y=[4,5,6,4,3]
z=np.prod([x,y],axis=1)
z

array([ 120, 1440])

In [133]:
# Cummulative Product
x=np.array([1, 2, 3, 4])
print(np.cumprod(x))

[ 1  2  6 24]


# NumPy Differences


In [134]:
x=np.array([1, 5, 8, 9])
print(np.diff(x))

[4 3 1]


In [135]:
#  for [1, 2, 3, 4], the discrete difference with n = 2
#     would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, 
#     since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]
x=np.array([1, 5, 8, 9])
y=np.diff(x,n=2)
y

array([-1, -2])

# NumPy LCM

In [136]:
x=2
y=6
print(np.lcm(x,y))

6


In [137]:
x=np.array([2,6,12])
print(np.lcm.reduce(x))

12


In [138]:
x=np.arange(1,11)
print(np.lcm.reduce(x))

2520


# NumPy GCD (HCF)

In [139]:
x=42
y=8
print(np.gcd(x,y))


2


In [140]:
x=np.array([2,6,12])
print(np.gcd.reduce(x))

2


# NumPy Trigonometric Functions

In [141]:
x = np.sin(np.pi/2)
print(x)

1.0


In [142]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [143]:
# Degrees to Radians 
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x) 

[1.57079633 3.14159265 4.71238898 6.28318531]


In [144]:
# Radians to Degrees
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [145]:
# Finding Angles
# NumPy provides ufuncs arcsin(), arccos() and arctan()
# that produce radian values for corresponding sin, cos and tan values given.
x = np.arcsin(1.0)
print(x)

1.5707963267948966


In [146]:
# Hypotenues
base=10
perp=3
x = np.hypot(base, perp)
x

10.44030650891055

# Hyperbolic Functions

In [147]:
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [148]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [149]:
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


# NumPy Set Operations

In [150]:
# union
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,4,3])
z=np.union1d(x,y)
z


array([1, 2, 3, 4, 5, 6])

In [151]:
# intersection
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,4,3])
z=np.intersect1d(x,y,assume_unique=True)
z

array([3, 4, 4, 5])

In [152]:
# Difference
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,4,3])
z=np.setdiff1d(x,y,assume_unique=True)
z

array([1, 2])

In [153]:
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,4,3])
z=np.setxor1d(x,y,assume_unique=True)
z

array([1, 2, 6])